In [2]:
import pandas as pd
import numpy as np

In [3]:
matches = pd.read_csv(
    "../data/processed/advanced_model_input.csv"
)

In [4]:
matches.head()

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,...,home_defense_avg,away_defense_avg,away_form,home_win,win_streak,home_loss,loss_streak,home_attack_avg,away_attack_avg,home_form
0,9,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False,...,1.4,3.0,0.4,1,3.0,0,2.0,3.0,1.4,0.6
1,10,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False,...,1.4,4.2,0.4,1,3.0,0,2.0,4.2,1.4,0.6
2,11,1879-01-18,England,Wales,2.0,1.0,Friendly,London,England,False,...,1.6,3.8,0.4,1,3.0,0,2.0,3.8,1.6,0.6
3,12,1879-04-05,England,Scotland,5.0,4.0,Friendly,London,England,False,...,1.8,4.6,0.2,1,4.0,0,1.0,4.6,1.8,0.8
4,13,1879-04-07,Wales,Scotland,0.0,3.0,Friendly,Wrexham,Wales,False,...,2.0,4.6,0.2,0,4.0,1,1.0,4.6,2.0,0.8

In [5]:
matches["home_advantage"] = np.where(
    matches["neutral"] == False,
    1,
    0
)

In [6]:
matches[
[
"neutral",
"home_advantage"
]
].head()

   neutral  home_advantage
0    False               1
1    False               1
2    False               1
3    False               1
4    False               1

In [7]:
peso_torneio = {

"Friendly":1,

"UEFA Nations League":2,

"FIFA World Cup qualification":3,

"UEFA Euro qualification":3,

"Confederations Cup":4,

"FIFA World Cup":5

}

In [8]:
matches["tournament_weight"] = (
    matches["tournament"]
    .map(
        peso_torneio
    )
)

In [9]:
matches[
"tournament_weight"
] = matches[
"tournament_weight"
].fillna(2)

In [10]:
matches[
[
"tournament",
"tournament_weight"
]
].head(20)

   tournament  tournament_weight
0    Friendly                1.0
1    Friendly                1.0
2    Friendly                1.0
3    Friendly                1.0
4    Friendly                1.0
5    Friendly                1.0
6    Friendly                1.0
7    Friendly                1.0
8    Friendly                1.0
9    Friendly                1.0
10   Friendly                1.0
11   Friendly                1.0
12   Friendly                1.0
13   Friendly                1.0
14   Friendly                1.0
15   Friendly                1.0
16   Friendly                1.0
17   Friendly                1.0
18   Friendly                1.0
19   Friendly                1.0

In [35]:
continentes = {

# ======================
# América do Sul
# ======================

"Brazil":"South America",
"Argentina":"South America",
"Uruguay":"South America",
"Chile":"South America",
"Colombia":"South America",
"Peru":"South America",
"Paraguay":"South America",
"Ecuador":"South America",
"Bolivia":"South America",
"Venezuela":"South America",
"Guyana":"South America",
"Suriname":"South America",
"French Guiana":"South America",

# ======================
# Europa
# ======================

"France":"Europe",
"Germany":"Europe",
"Spain":"Europe",
"Italy":"Europe",
"England":"Europe",
"Portugal":"Europe",
"Belgium":"Europe",
"Netherlands":"Europe",
"Croatia":"Europe",
"Poland":"Europe",
"Switzerland":"Europe",
"Austria":"Europe",
"Denmark":"Europe",
"Sweden":"Europe",
"Norway":"Europe",
"Finland":"Europe",
"Ireland":"Europe",
"Northern Ireland":"Europe",
"Scotland":"Europe",
"Wales":"Europe",
"Ukraine":"Europe",
"Russia":"Europe",
"Serbia":"Europe",
"Montenegro":"Europe",
"Bosnia and Herzegovina":"Europe",
"Slovenia":"Europe",
"Slovakia":"Europe",
"Czech Republic":"Europe",
"Hungary":"Europe",
"Romania":"Europe",
"Bulgaria":"Europe",
"Greece":"Europe",
"Turkey":"Europe",
"Albania":"Europe",
"Iceland":"Europe",
"Luxembourg":"Europe",
"Bosnia And Herzegovina":"Europe",
"Republic Of Ireland":"Europe",
"North Macedonia":"Europe",
"Kosovo":"Europe",
"Belarus":"Europe",
"Georgia":"Europe",
"Armenia":"Europe",
"Azerbaijan":"Europe",
"Cyprus":"Europe",
"Estonia":"Europe",
"Latvia":"Europe",
"Lithuania":"Europe",
"Faroe Islands":"Europe",
"Gibraltar":"Europe",
"San Marino":"Europe",
"Liechtenstein":"Europe",
"Malta":"Europe",
"Luxembourg":"Europe",
"Monaco":"Europe",

# Ex-seleções

"Yugoslavia":"Europe",
"Czechoslovakia":"Europe",
"German Dr":"Europe",
"Saarland":"Europe",

# ======================
# América do Norte
# ======================

"USA":"North America",
"United States":"North America",
"Mexico":"North America",
"Canada":"North America",
"Costa Rica":"North America",
"Panama":"North America",
"Honduras":"North America",
"El Salvador":"North America",
"Guatemala":"North America",
"Jamaica":"North America",
"Haiti":"North America",
"Trinidad and Tobago":"North America",
"Cuba":"North America",
"Dominican Republic":"North America",
"Trinidad And Tobago":"North America",
"Puerto Rico":"North America",
"Guadeloupe":"North America",
"Martinique":"North America",
"Curaçao":"North America",
"Aruba":"North America",
"Bermuda":"North America",
"Bahamas":"North America",
"Barbados":"North America",
"Dominica":"North America",
"Saint Lucia":"North America",
"Saint Kitts And Nevis":"North America",
"Saint Vincent And The Grenadines":"North America",
"Antigua And Barbuda":"North America",
"Cayman Islands":"North America",
"British Virgin Islands":"North America",
"United States Virgin Islands":"North America",
"Turks And Caicos Islands":"North America",
"Montserrat":"North America",

# ======================
# África
# ======================

"Morocco":"Africa",
"Egypt":"Africa",
"Nigeria":"Africa",
"Cameroon":"Africa",
"Senegal":"Africa",
"Ghana":"Africa",
"Tunisia":"Africa",
"Algeria":"Africa",
"Mali":"Africa",
"South Africa":"Africa",
"Ivory Coast":"Africa",
"Cote d'Ivoire":"Africa",
"DR Congo":"Africa",
"Congo":"Africa",
"Angola":"Africa",
"Zambia":"Africa",
"Uganda":"Africa",
"Kenya":"Africa",
"Tanzania":"Africa",
"Ethiopia":"Africa",
"Cape Verde":"Africa",
"South Sudan":"Africa",
"Sudan":"Africa",
"Zimbabwe":"Africa",
"Uganda":"Africa",
"Rwanda":"Africa",
"Burkina Faso":"Africa",
"Benin":"Africa",
"Togo":"Africa",
"Niger":"Africa",
"Chad":"Africa",
"Central African Republic":"Africa",
"Gabon":"Africa",
"Guinea":"Africa",
"Guinea-Bissau":"Africa",
"Liberia":"Africa",
"Sierra Leone":"Africa",
"Somalia":"Africa",
"Somaliland":"Africa",
"Djibouti":"Africa",
"Eritrea":"Africa",
"Mauritania":"Africa",
"Comoros":"Africa",
"Seychelles":"Africa",
"São Tomé And Príncipe":"Africa",
"Eswatini":"Africa",
"Lesotho":"Africa",
"Libya":"Africa",

# ======================
# Ásia
# ======================

"Japan":"Asia",
"South Korea":"Asia",
"Korea Republic":"Asia",
"Iran":"Asia",
"Iraq":"Asia",
"Saudi Arabia":"Asia",
"Qatar":"Asia",
"United Arab Emirates":"Asia",
"UAE":"Asia",
"Oman":"Asia",
"Bahrain":"Asia",
"Kuwait":"Asia",
"Syria":"Asia",
"Jordan":"Asia",
"India":"Asia",
"China":"Asia",
"China PR":"Asia",
"Thailand":"Asia",
"Vietnam":"Asia",
"Indonesia":"Asia",
"Malaysia":"Asia",
"Uzbekistan":"Asia",
"Kazakhstan":"Asia",
"Afghanistan":"Asia",
"Bangladesh":"Asia",
"Bhutan":"Asia",
"Cambodia":"Asia",
"Laos":"Asia",
"Lebanon":"Asia",
"Kyrgyzstan":"Asia",
"Tajikistan":"Asia",
"Turkmenistan":"Asia",
"Nepal":"Asia",
"Pakistan":"Asia",
"Palestine":"Asia",
"Macau":"Asia",
"Hong Kong":"Asia",
"Taiwan":"Asia",
"North Korea":"Asia",
"Myanmar":"Asia",
"Philippines":"Asia",
"Singapore":"Asia",
"Sri Lanka":"Asia",
"Timor-Leste":"Asia",
"Yemen":"Asia",
"Yemen Dpr":"Asia",
"Vietnam Republic":"Asia",
"North Vietnam":"Asia",

# ======================
# Oceania
# ======================

"Australia":"Oceania",
"New Zealand":"Oceania",
"Fiji":"Oceania",
"Tahiti":"Oceania",
"Papua New Guinea":"Oceania",
"Solomon Islands":"Oceania",
"Vanuatu":"Oceania",
"Samoa":"Oceania",
"American Samoa":"Oceania",
"Cook Islands":"Oceania",
"Tonga":"Oceania",
"Kiribati":"Oceania",
"Tuvalu":"Oceania",
"Niue":"Oceania",
"New Caledonia":"Oceania",
"Papua New Guinea":"Oceania",
"Solomon Islands":"Oceania",
"Vanuatu":"Oceania",
"Wallis Islands And Futuna":"Oceania"

}

In [36]:
matches[
"home_continent"
] = matches[
"home_team"
].map(
continentes
)

matches[
"away_continent"
] = matches[
"away_team"
].map(
continentes
)

In [37]:
matches[
[
"home_team",
"home_continent",
"away_team",
"away_continent"
]
].head(10)

  home_team home_continent away_team away_continent
0  Scotland         Europe   England         Europe
1  Scotland         Europe     Wales         Europe
2   England         Europe     Wales         Europe
3   England         Europe  Scotland         Europe
4     Wales         Europe  Scotland         Europe
5  Scotland         Europe   England         Europe
6     Wales         Europe   England         Europe
7  Scotland         Europe     Wales         Europe
8   England         Europe     Wales         Europe
9   England         Europe  Scotland         Europe

In [45]:
mapa_continentes = {

"South America":1,

"Europe":2,

"North America":3,

"Asia":4,

"Africa":5,

"Oceania":6

}

In [39]:
matches["home_continent"] = (
    matches["home_team"]
    .map(continentes)
)

matches["away_continent"] = (
    matches["away_team"]
    .map(continentes)
)

In [40]:
print(
matches[
[
"home_continent",
"away_continent"
]
].isnull().sum()
)

home_continent    4485
away_continent    4662
dtype: int64

In [41]:
faltantes_home = matches.loc[
    matches["home_continent"].isna(),
    "home_team"
].unique()

print(
sorted(
faltantes_home
)
)

['Abkhazia', 'Alderney', 'Andalusia', 'Andorra', 'Anguilla', 'Arameans Suryoye', 'Artsakh', 'Aymara', 'Barawa', 'Basque Country', 'Belize', 'Biafra', 'Bonaire', 'Botswana', 'Brittany', 'Brunei', 'Burundi', 'Canary Islands', 'Cascadia', 'Catalonia', 'Central Spain', 'Chagos Islands', 'Chameria', 'Chechnya', 'China Pr', 'Corsica', 'County Of Nice', 'Darfur', 'Donetsk Pr', 'Dr Congo', 'Délvidék', 'Elba Island', 'Ellan Vannin', 'Equatorial Guinea', 'Falkland Islands', 'Felvidék', 'Franconia', 'Frøya', 'Galicia', 'Gambia', 'Gotland', 'Gozo', 'Greenland', 'Grenada', 'Guam', 'Guernsey', 'Găgăuzia', 'Hitra', 'Hmong', 'Iraqi Kurdistan', 'Isle Of Man', 'Isle Of Wight', 'Israel', 'Jersey', 'Kabylia', 'Kernow', 'Kárpátalja', 'Luhansk Pr', 'Madagascar', 'Madrid', 'Malawi', 'Maldives', 'Manchukuo', 'Mapuche', 'Marshall Islands', 'Matabeleland', 'Mauritius', 'Mayotte', 'Menorca', 'Micronesia', 'Moldova', 'Mongolia', 'Mozambique', 'Namibia', 'Nicaragua', 'Northern Cyprus', 'Northern Mariana Islands', 'Occitania', 'Orkney', 'Padania', 'Palau', 'Panjab', 'Parishes Of Jersey', 'Provence', 'Raetia', 'Republic Of St. Pauli', 'Rhodes', 'Romani People', 'Ryūkyū', 'Réunion', 'Saare County', 'Saint Barthélemy', 'Saint Helena', 'Saint Martin', 'Saint Pierre And Miquelon', 'Sark', 'Saugeais', 'Sealand', 'Seborga', 'Shetland', 'Silesia', 'Sint Maarten', 'South Ossetia', 'Székely Land', 'Sápmi', 'Tamil Eelam', 'Tibet', 'Ticino', 'United Koreans In Japan', 'Vatican City', 'West Papua', 'Western Armenia', 'Western Australia', 'Western Isles', 'Western Sahara', 'Ynys Môn', 'Yorkshire', 'Yoruba Nation', 'Zanzibar', 'Åland Islands']

In [42]:
faltantes_away = matches.loc[
    matches["away_continent"].isna(),
    "away_team"
].unique()

print(
sorted(
faltantes_away
)
)

['Abkhazia', 'Alderney', 'Ambazonia', 'Andalusia', 'Andorra', 'Anguilla', 'Arameans Suryoye', 'Artsakh', 'Asturias', 'Aymara', 'Barawa', 'Basque Country', 'Belize', 'Biafra', 'Bonaire', 'Botswana', 'Brittany', 'Brunei', 'Burundi', 'Cascadia', 'Catalonia', 'Central Spain', 'Chagos Islands', 'Chameria', 'Chechnya', 'China Pr', 'Cilento', 'Corsica', 'County Of Nice', 'Crimea', 'Darfur', 'Donetsk Pr', 'Dr Congo', 'Ellan Vannin', 'Equatorial Guinea', 'Falkland Islands', 'Felvidék', 'Franconia', 'Frøya', 'Galicia', 'Gambia', 'Gotland', 'Gozo', 'Greenland', 'Grenada', 'Guam', 'Guernsey', 'Hitra', 'Hmong', 'Iraqi Kurdistan', 'Isle Of Man', 'Isle Of Wight', 'Israel', 'Jersey', 'Kabylia', 'Kernow', 'Kárpátalja', 'Luhansk Pr', 'Madagascar', 'Malawi', 'Maldives', 'Manchukuo', 'Marshall Islands', 'Matabeleland', 'Maule Sur', 'Mauritius', 'Mayotte', 'Menorca', 'Micronesia', 'Moldova', 'Mongolia', 'Mozambique', 'Namibia', 'Nicaragua', 'Northern Cyprus', 'Northern Mariana Islands', 'Occitania', 'Orkney', 'Padania', 'Panjab', 'Parishes Of Jersey', 'Provence', 'Raetia', 'Rhodes', 'Romani People', 'Réunion', 'Saare County', 'Saint Barthélemy', 'Saint Helena', 'Saint Martin', 'Saint Pierre And Miquelon', 'Sark', 'Sealand', 'Shetland', 'Sint Maarten', 'South Ossetia', 'South Yemen', 'Surrey', 'Székely Land', 'Sápmi', 'Tamil Eelam', 'Tibet', 'Ticino', 'Two Sicilies', 'United Koreans In Japan', 'Vatican City', 'Western Armenia', 'Western Australia', 'Western Isles', 'Western Sahara', 'Ynys Môn', 'Yorkshire', 'Zanzibar', 'Åland Islands']

In [43]:
matches[
[
"home_team",
"home_continent",

"away_team",
"away_continent"
]
].head()

  home_team home_continent away_team away_continent
0  Scotland         Europe   England         Europe
1  Scotland         Europe     Wales         Europe
2   England         Europe     Wales         Europe
3   England         Europe  Scotland         Europe
4     Wales         Europe  Scotland         Europe

In [ ]:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\Samsung\Desktop\copapredict-ia\venv\Lib\site-packages\pandas\core\indexes\base.py:3641, in Index.get_loc(self, key)
   3640 try:
-> 3641     return self._engine.get_loc(casted_key)
   3642 except KeyError as err:

File pandas/_libs/index.pyx:168, in pandas._libs.index.IndexEngine.get_loc()
--> 168 'Could not get source, probably due dynamically evaluated source code.'

File pandas/_libs/index.pyx:197, in pandas._libs.index.IndexEngine.get_loc()
--> 197 'Could not get source, probably due dynamically evaluated source code.'

File pandas/_libs/hashtable_class_helper.pxi:7668, in pandas._libs.hashtable.PyObjectHashTable.get_item()
-> 7668 'Could not get source, probably due dynamically evaluated source code.'

File pandas/_libs/hashtable_class_helper.pxi:7676, in pandas._libs.hashtable.PyObjectHashTable.get_item()
-> 7676 'Could not get source, probably due dynamically evaluated source code.'

KeyError: 'home_continent_code'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[46], line 5
...
   3651     #  InvalidIndexError. Otherwise we fall through and re-raise
   3652     #  the TypeError.
   3653     self._check_indexing_error(key)

KeyError: 'home_continent_code'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

KeyError: 'home_continent_code'